spring:
  application:
    name: transferencia

application:
  contas:
    url: http://localhost:9090/contas/
  clientes:
    url: http://localhost:9090/clientes/
  transferencias:
    url: http://localhost:9090/contas/saldos

server:
  port: 8090